version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "."
    schedule:
      interval: "weekly"
    target-branch: "development"

  # Root package.json
  - package-ecosystem: "npm"
    directory: "."
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    target-branch: "development"

  # Client package.json
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    target-branch: "development"

  # Server package.json
  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    target-branch: "development"
