name: cta-tracker

services:
  nginx:
    restart: always
    image: 
      'nginx:latest'
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 3051:3051
    depends_on:
      - server
      - client

  mongodb:
    image: mongo:latest
    container_name: mongodb_server
    volumes:
      - mongo_data:/data/db
    networks:
      - cta-tracker
    env_file: ./.env
    ports:
      - 27017:27017

  server:
    build:
      context: './server'
      dockerfile: Dockerfile
    restart: always
    container_name: backend
    env_file:
      - ./.env
    volumes:
      - './server:/app'
      - '/app/node_modules'
    networks:
      - cta-tracker
    environment:
      - ATLAS_USER=$ATLAS_USER
      - ATLAS_PWD=$ATLAS_PWD
      - CTA_TRAIN_API_KEY=$CTA_TRAIN_API_KEY
      - FRONTEND_URL=$FRONTEND_URL
      - TRAIN_ARRIVALS=$TRAIN_ARRIVALS
      - MONGO_LINK=$MONGO_LINK
    ports:
      - 3000:3000
    depends_on:
      - mongodb

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    container_name: frontend
    env_file:
      - ./.env
    environment:
      - GOOGLE_KEY=$GOOGLE_KEY
      - SERVER_URL=$SERVER_URL
    volumes:
      - './client:/app'
      - '/app/node_modules'
    networks:
      - cta-tracker
    ports:
      - 8080:8080
    depends_on:
      - server
    expose:
      - 8080
    command: yarn run dev
    stdin_open: true
    tty: true

volumes:
  mongo_data:
networks:
  cta-tracker:
    driver: bridge